[package]
name = "db_deleter"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "mysql", "chrono"] }
dotenvy = "0.15"
csv = "1.3"
chrono = { version = "0.4", features = ["serde"] }